// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "FINNEY":return img`
.........ffffffff........
.......fffffffffff.......
......fffffffffffff......
......fffffffffffff......
......fffffffffffff......
.......ffffffffffff......
........ffffffffff.......
.........fffffff.........
........ffffffff.........
.......fffffdffff........
.......ffffddddfff.......
.......ff11dd11dff.......
......fdd1fddf1ddf.......
......fddddddddddf.......
.......fddd33dddff.......
........fddddddf.........
.........ffddfff.........
.......ff11dd111f........
.......f111dd1111f.......
......f11111111111f......
......f11111111111f......
......fdd1111111ddf......
....fffdd1111111ddfff....
....fdddd1111111ddddf....
....fdddd1111111ddddf....
....fffff8888888fffff....
........f8888888f........
........f8888888f........
........f88fff88f........
........f88f.f88f........
........f88f.f88f........
........f88f.f88f........
........ffff.ffff........
......fff22f.f22fff......
......f22fff.fff22f......
......f2ff2f.f2ff2f......
......f1111f.f1111f......
......ffffff.ffffff......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
